baseURL = "/"
languageCode = "en-us"
title = "Hugo Up"

# disable taxonomies default pages
#disableKinds = ["taxonomy", "taxonomyTerm", "categories"]
googleAnalytics = ""

# include to use theme
#theme = "example-theme"
enableRobotsTXT = true

# used for code blocks
pygmentsCodeFences = true
pygmentsUseClasses = true

canonifyURLS = true
paginate = 12

[taxonomies]
  category = "categories"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"